drop table if exists member CASCADE;
drop table if exists board CASCADE;
create table member
(
 id bigint generated by default as identity,
 userid varchar(255),
 password varchar(255),
 primary key (id)
);

create table board
(
 id bigint generated by default as identity,
 writer varchar(255),
 title varchar(255),
 text varchar(2000),
 date date default current_date
);